[workspace]
members = [
    "crates/bg-remove-core",
    "crates/bg-remove-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["IMG.LY Rust Team <rust@img.ly>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/imgly/background-removal-rust"
homepage = "https://img.ly"
keywords = ["background-removal", "image-processing", "computer-vision", "onnx", "segmentation"]
categories = ["multimedia::images", "computer-vision", "science"]
rust-version = "1.70"

[workspace.dependencies]
# Core dependencies
ort = "2.0.0-rc.10"
image = { version = "0.24", features = ["png", "jpeg", "webp"] }
ndarray = "0.16"
anyhow = "1.0"
thiserror = "1.0"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# CLI dependencies  
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
env_logger = "0.10"
log = "0.4"

# Development dependencies
criterion = "0.5"
tempfile = "3.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true


[profile.dev]
opt-level = 1
debug = true

# Features for model embedding  
[workspace.metadata.features]
default = ["fp16-model"]
fp16-model = ["balanced-performance", "90mb-binary"]
fp32-model = ["high-accuracy", "175mb-binary"]