[package]
name = "bg-remove-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "Core background removal library using ONNX Runtime and ISNet models"

[features]
# Default: FP16 model (balanced performance, ~90MB binary)
default = ["fp16-model"]

# Model precision selection (mutually exclusive)
fp16-model = []           # Embed FP16 model (smaller, faster)
fp32-model = []           # Embed FP32 model (higher precision, ~175MB binary)

# Legacy compatibility
isnet-fp16 = ["fp16-model"]
isnet-standard = ["fp32-model"]

[dependencies]
# Core dependencies
ort = { workspace = true }
image = { workspace = true }
ndarray = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# Async runtime
tokio = { workspace = true, optional = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Logging
log = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[build-dependencies]
# For embedding model files during build (placeholder for now)
# std-fs = "0.1"