[package]
name = "bg-remove-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "Core background removal library using ONNX Runtime and ISNet models"

# Inherit workspace lints for zero-warning policy
[lints]
workspace = true

[features]
# Default: FP16 model (balanced performance, ~90MB binary)
default = ["fp16-model"]

# Model precision selection (mutually exclusive)
fp16-model = []           # Embed FP16 model (smaller, faster)
fp32-model = []           # Embed FP32 model (higher precision, ~175MB binary)

# Legacy compatibility
isnet-fp16 = ["fp16-model"]
isnet-standard = ["fp32-model"]

# Development features
benchmark-details = []    # Enable detailed benchmark output

[dependencies]
# Core dependencies
ort = { workspace = true }
image = { workspace = true }
ndarray = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# Async runtime
tokio = { workspace = true, optional = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Logging
log = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
env_logger = "0.11"

[[bench]]
name = "background_removal"
harness = false

[[bench]]
name = "simple_bench"
harness = false

[build-dependencies]
serde_json = { workspace = true }