name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cache vcpkg packages (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v3
      with:
        path: |
          C:\vcpkg\installed
          C:\vcpkg\packages
        key: ${{ runner.os }}-vcpkg-ffmpeg-v2
        restore-keys: |
          ${{ runner.os }}-vcpkg-ffmpeg-

    - name: Install FFmpeg (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev

    - name: Install FFmpeg (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install ffmpeg

    - name: Install FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Install pkg-config for Windows first
        choco install pkgconfiglite -y
        
        # vcpkg is pre-installed on GitHub Actions Windows runners
        # Install FFmpeg with development files (using correct vcpkg syntax)
        C:\vcpkg\vcpkg.exe install ffmpeg:x64-windows
        
        # Set environment variables
        echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
        echo "C:\vcpkg\installed\x64-windows\bin" >> $env:GITHUB_PATH
        echo "FFMPEG_DIR=C:\vcpkg\installed\x64-windows" >> $env:GITHUB_ENV
        echo "PKG_CONFIG_PATH=C:\vcpkg\installed\x64-windows\lib\pkgconfig" >> $env:GITHUB_ENV
        
        # Check what vcpkg actually installed
        Write-Host "Checking installed files in bin directory:"
        Get-ChildItem C:\vcpkg\installed\x64-windows\bin -ErrorAction SilentlyContinue | Select-Object -First 20
        
        Write-Host "`nChecking installed files in tools directory:"
        Get-ChildItem C:\vcpkg\installed\x64-windows\tools -ErrorAction SilentlyContinue | Select-Object -First 20
        
        # Verify development files exist (these are what we really need)
        Write-Host "`nChecking include directories:"
        Get-ChildItem C:\vcpkg\installed\x64-windows\include\libav* -Directory -ErrorAction SilentlyContinue
        
        Write-Host "`nChecking library files:"
        Get-ChildItem C:\vcpkg\installed\x64-windows\lib\*.lib -ErrorAction SilentlyContinue | Select-Object -First 10
        
        Write-Host "`nChecking pkgconfig files:"
        Get-ChildItem C:\vcpkg\installed\x64-windows\lib\pkgconfig\*.pc -ErrorAction SilentlyContinue
        
        # The ffmpeg-sys-next crate needs the libraries, not the executable
        # So we just verify the libraries are present
        if (Test-Path "C:\vcpkg\installed\x64-windows\lib\avcodec.lib") {
            Write-Host "`nFFmpeg libraries successfully installed!"
        } else {
            Write-Error "FFmpeg libraries not found!"
            exit 1
        }

    - name: Check
      run: cargo check --verbose

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose