name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install FFmpeg (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev

    - name: Install FFmpeg (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install ffmpeg

    - name: Install FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Install pkg-config first
        choco install pkgconfiglite -y
        
        # Download pre-built FFmpeg binaries with development files
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1-full_build-shared.7z" -OutFile "ffmpeg.7z"
        
        # Install 7-zip to extract the archive
        choco install 7zip -y
        
        # Extract FFmpeg
        & "C:\Program Files\7-Zip\7z.exe" x ffmpeg.7z -oC:\ffmpeg_temp -y
        
        # Move to final location
        $ffmpegDir = Get-ChildItem -Path "C:\ffmpeg_temp" -Directory | Select-Object -First 1
        Move-Item -Path $ffmpegDir.FullName -Destination "C:\ffmpeg"
        
        # Set environment variables
        echo "C:\ffmpeg\bin" >> $env:GITHUB_PATH
        echo "FFMPEG_DIR=C:\ffmpeg" >> $env:GITHUB_ENV
        echo "PKG_CONFIG_PATH=C:\ffmpeg\lib\pkgconfig" >> $env:GITHUB_ENV
        
        # Verify FFmpeg installation
        C:\ffmpeg\bin\ffmpeg.exe -version
        
        # Check that development files exist
        Get-ChildItem -Path "C:\ffmpeg\include" -Recurse -Filter "*.h" | Select-Object -First 5
        Get-ChildItem -Path "C:\ffmpeg\lib" -Filter "*.lib" | Select-Object -First 5

    - name: Check
      run: cargo check --verbose

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose