name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install FFmpeg (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev

    - name: Install FFmpeg (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install ffmpeg

    - name: Install FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Download prebuilt FFmpeg libraries
        Invoke-WebRequest -Uri "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip" -OutFile "ffmpeg.zip"
        Expand-Archive -Path "ffmpeg.zip" -DestinationPath "C:\ffmpeg"
        $ffmpegPath = Get-ChildItem -Path "C:\ffmpeg" -Directory | Select-Object -First 1
        
        # Set environment variables for FFmpeg
        echo "FFMPEG_DIR=$($ffmpegPath.FullName)" >> $env:GITHUB_ENV
        echo "$($ffmpegPath.FullName)\bin" >> $env:GITHUB_PATH
        
        # Create pkg-config files for FFmpeg libraries
        $pkgConfigPath = "C:\pkg-config"
        New-Item -ItemType Directory -Force -Path $pkgConfigPath
        
        # Create libavutil.pc
        @"
prefix=$($ffmpegPath.FullName)
exec_prefix=`${prefix}
libdir=`${prefix}/lib
includedir=`${prefix}/include

Name: libavutil
Description: FFmpeg utility library
Version: 58.2.100
Libs: -L`${libdir} -lavutil
Cflags: -I`${includedir}
"@ | Out-File -FilePath "$pkgConfigPath\libavutil.pc" -Encoding ASCII
        
        # Create similar files for other libraries
        $libs = @("avcodec", "avformat", "avfilter", "avdevice", "swresample", "swscale")
        foreach ($lib in $libs) {
          @"
prefix=$($ffmpegPath.FullName)
exec_prefix=`${prefix}
libdir=`${prefix}/lib
includedir=`${prefix}/include

Name: lib$lib
Description: FFmpeg $lib library
Version: 58.2.100
Libs: -L`${libdir} -l$lib
Cflags: -I`${includedir}
"@ | Out-File -FilePath "$pkgConfigPath\lib$lib.pc" -Encoding ASCII
        }
        
        # Set PKG_CONFIG_PATH
        echo "PKG_CONFIG_PATH=$pkgConfigPath" >> $env:GITHUB_ENV
        
        # Install pkg-config
        choco install pkgconfiglite

    - name: Check
      run: cargo check --verbose

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose