name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install FFmpeg (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev

    - name: Install FFmpeg (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install ffmpeg

    - name: Install FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Install FFmpeg using Chocolatey
        choco install ffmpeg-full -y
        
        # Refresh environment variables
        refreshenv
        
        # Set FFmpeg directory environment variable
        $ffmpegPath = (Get-Command ffmpeg).Path | Split-Path | Split-Path
        echo "FFMPEG_DIR=$ffmpegPath" >> $env:GITHUB_ENV
        
        # Verify FFmpeg installation
        ffmpeg -version

    - name: Check
      run: cargo check --verbose ${{ matrix.os == 'windows-latest' && '--no-default-features --features onnx,tract,cli,webp-support' || '' }}

    - name: Build
      run: cargo build --verbose ${{ matrix.os == 'windows-latest' && '--no-default-features --features onnx,tract,cli,webp-support' || '' }}

    - name: Test
      run: cargo test --verbose ${{ matrix.os == 'windows-latest' && '--no-default-features --features onnx,tract,cli,webp-support' || '' }}